version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev:
        dependency-type: "development"
      prod:
        dependency-type: "production"
