version: '3'
services:
  http-server-go:
    image: golang:1.22
    environment:
      # You can override any env var present in ./impl/http-server-go/config.go
      - RBTX_API_KEY=NkCH56YZfP9psrycDLVk
      - RBTX_PATH_PREFIX=cd5331ba
      - RBTX_PORT=9001
    ports:
      - "9001:9001"
    volumes:
      - .docker/go:/go
      - ./impl/http-server-go:/app
    working_dir: "/app"
    command: >
      bash -c "go fmt
      && go run main.go config.go data.go errors.go handlers.go middlewares.go service.go service_noop.go service_self.go utils.go"
  swagger-ui:
    image: swaggerapi/swagger-ui:v5.12.0
    environment:
      - PORT=9002
      - SWAGGER_JSON=/spec/swagger.json
    ports:
      - "9002:9002"
    volumes:
      - ./spec/_generated:/spec
