version: '3'
services:
  http-server-go:
    image: golang:1.22
    environment:
      # You can override any config value present in ./impl/http-server-go/config.go
      - RBTX_API_KEY=${RBTX_API_KEY:-NkCH56YZfP9psrycDLVk}
      - RBTX_PATH_PREFIX=${RBTX_PATH_PREFIX:-cd5331ba}
      - RBTX_DASHBOARD_SERVICE_FILE_JSON_FILE_PATH=${RBTX_DASHBOARD_SERVICE_FILE_JSON_FILE_PATH:-/data/dashboards.example.json}
      - RBTX_DASHBOARD_SERVICE_IMPL=${RBTX_DASHBOARD_SERVICE_IMPL:-fileJson}
      - RBTX_PORT=9001
      - RBTX_RUNNABLE_SERVICE_FILE_JSON_FILE_PATH=${RBTX_RUNNABLE_SERVICE_FILE_JSON_FILE_PATH:-/data/servers.example.json}
      - RBTX_RUNNABLE_SERVICE_IMPL=${RBTX_RUNNABLE_SERVICE_IMPL:-noop}
    ports:
      - "9001:9001"
    volumes:
      - ./data:/data
      - ./impl/http-server-go:/app
    working_dir: "/app"
    command: bash -c "go fmt && go build -o /build/http-server-go -v && /build/http-server-go"
  swagger-ui:
    image: swaggerapi/swagger-ui:v5.12.0
    environment:
      - PORT=9002
      - SWAGGER_JSON=/spec/swagger.json
    ports:
      - "9002:9002"
    volumes:
      - ./spec/_generated:/spec
